-- SandLicense v0.1.0 fresh installation only. Execute via an explicitly authorized SandPackage lifecycle.
-- All timestamps are UTC stored without a timezone. No database creation or legacy import.
CREATE TABLE sand_license_product (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 organization_id bigint NOT NULL,
 application_id bigint,
 code varchar(80) NOT NULL,
 name varchar(120) NOT NULL,
 audience varchar(240) NOT NULL,
 state varchar(20) NOT NULL DEFAULT 'draft' CHECK(state IN ('draft','published')),
 published_time timestamp(0) without time zone,
 status smallint NOT NULL DEFAULT 1 CHECK (status IN (1,2)),
 created_by bigint, updated_by bigint,
 create_time timestamp(0) without time zone NOT NULL,
 update_time timestamp(0) without time zone NOT NULL,
 delete_time timestamp(0) without time zone,
 CONSTRAINT sand_license_product_code_unique UNIQUE(code)
);
CREATE INDEX sand_license_product_organization_idx ON sand_license_product(organization_id);
CREATE TABLE sand_license_plan (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id bigint NOT NULL REFERENCES sand_license_product(id),
 code varchar(80) NOT NULL, name varchar(120) NOT NULL,
 revision integer NOT NULL DEFAULT 1 CHECK (revision>0),
 kind varchar(20) NOT NULL CHECK(kind IN ('desktop','membership')),
 duration_unit varchar(10) NOT NULL CHECK(duration_unit IN ('day','month','year')),
 duration_value integer NOT NULL CHECK(duration_value BETWEEN 1 AND 10000),
 seat_limit integer NOT NULL DEFAULT 1 CHECK(seat_limit BETWEEN 1 AND 10000),
 features jsonb NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(features)='object'),
 state varchar(20) NOT NULL DEFAULT 'draft' CHECK(state IN ('draft','published')),
 published_time timestamp(0) without time zone,
 status smallint NOT NULL DEFAULT 1 CHECK(status IN (1,2)),
 created_by bigint, updated_by bigint,
 create_time timestamp(0) without time zone NOT NULL,
 update_time timestamp(0) without time zone NOT NULL,
 delete_time timestamp(0) without time zone,
 CONSTRAINT sand_license_plan_revision_unique UNIQUE(product_id,code,revision)
);
CREATE TABLE sand_license_sku_mapping (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id bigint NOT NULL REFERENCES sand_license_product(id),
 plan_id bigint NOT NULL REFERENCES sand_license_plan(id),
 channel_code varchar(80) NOT NULL, sku_code varchar(160) NOT NULL,
 status smallint NOT NULL DEFAULT 1 CHECK(status IN (1,2)),
 created_by bigint, updated_by bigint,
 create_time timestamp(0) without time zone NOT NULL,
 update_time timestamp(0) without time zone NOT NULL,
 delete_time timestamp(0) without time zone,
 CONSTRAINT sand_license_sku_mapping_unique UNIQUE(product_id,channel_code,sku_code)
);
CREATE TABLE sand_license_fulfillment (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id bigint NOT NULL REFERENCES sand_license_product(id),
 channel_code varchar(80) NOT NULL, order_id varchar(160) NOT NULL,
 order_item_id varchar(160) NOT NULL, payment_cycle_id varchar(160) NOT NULL,
 quantity integer NOT NULL CHECK(quantity BETWEEN 1 AND 1000),
 sku_code varchar(160) NOT NULL,
 plan_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
 subject_code varchar(160),
 cycle_start_time timestamp(0) without time zone,
 cycle_expire_time timestamp(0) without time zone,
 cancelled_time timestamp(0) without time zone,
 state varchar(20) NOT NULL CHECK(state IN ('pending','paid','refunded','chargeback')),
 request_hash char(64) NOT NULL,
 create_time timestamp(0) without time zone NOT NULL,
 update_time timestamp(0) without time zone NOT NULL,
 CONSTRAINT sand_license_fulfillment_source_unique UNIQUE(product_id,channel_code,order_item_id,payment_cycle_id),
 CONSTRAINT sand_license_fulfillment_cycle_check CHECK (
   (cycle_start_time IS NULL AND cycle_expire_time IS NULL) OR cycle_start_time < cycle_expire_time)
);
CREATE TABLE sand_license_fulfillment_event (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id bigint NOT NULL REFERENCES sand_license_product(id),
 channel_code varchar(80) NOT NULL, event_id varchar(160) NOT NULL,
 fulfillment_id bigint NOT NULL REFERENCES sand_license_fulfillment(id),
 event_type varchar(20) NOT NULL CHECK(event_type IN ('paid','refunded','chargeback','cancelled')),
 request_hash char(64) NOT NULL, result_ref jsonb NOT NULL DEFAULT '{}'::jsonb,
 create_time timestamp(0) without time zone NOT NULL,
 CONSTRAINT sand_license_fulfillment_event_unique UNIQUE(product_id,channel_code,event_id)
);
CREATE TABLE sand_license_entitlement (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id bigint NOT NULL REFERENCES sand_license_product(id),
 plan_snapshot jsonb NOT NULL,
 kind varchar(20) NOT NULL CHECK(kind IN ('desktop','membership')),
 subject_code varchar(160),
 state varchar(20) NOT NULL CHECK(state IN ('active','suspended','revoked')),
 start_time timestamp(0) without time zone NOT NULL,
 expire_time timestamp(0) without time zone NOT NULL,
 seat_limit integer NOT NULL DEFAULT 1 CHECK(seat_limit BETWEEN 1 AND 10000),
 create_time timestamp(0) without time zone NOT NULL,
 update_time timestamp(0) without time zone NOT NULL,
 CONSTRAINT sand_license_entitlement_interval_check CHECK(start_time<expire_time)
);
CREATE INDEX sand_license_entitlement_subject_idx ON sand_license_entitlement(product_id,subject_code);
CREATE TABLE sand_license_grant (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 entitlement_id bigint NOT NULL REFERENCES sand_license_entitlement(id),
 fulfillment_id bigint REFERENCES sand_license_fulfillment(id),
 source_unit_no integer NOT NULL DEFAULT 1 CHECK(source_unit_no>0),
 source_code varchar(160) NOT NULL,
 start_time timestamp(0) without time zone NOT NULL,
 expire_time timestamp(0) without time zone NOT NULL,
 state varchar(20) NOT NULL CHECK(state IN ('active','revoked')),
 revoked_time timestamp(0) without time zone,
 create_time timestamp(0) without time zone NOT NULL,
 update_time timestamp(0) without time zone NOT NULL,
 CONSTRAINT sand_license_grant_source_unique UNIQUE(fulfillment_id,source_unit_no),
 CONSTRAINT sand_license_grant_manual_unique UNIQUE(source_code),
 CONSTRAINT sand_license_grant_interval_check CHECK(start_time<expire_time)
);
CREATE TABLE sand_license_claim (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 fulfillment_id bigint NOT NULL REFERENCES sand_license_fulfillment(id),
 unit_no integer NOT NULL CHECK(unit_no>0),
 secret_hash char(64) NOT NULL,
 session_key_hash char(64),
 state varchar(20) NOT NULL CHECK(state IN ('ready','claimed','redeemed','revoked')),
 redemption_code_id bigint,
 expire_time timestamp(0) without time zone NOT NULL,
 create_time timestamp(0) without time zone NOT NULL,
 update_time timestamp(0) without time zone NOT NULL,
 CONSTRAINT sand_license_claim_unit_unique UNIQUE(fulfillment_id,unit_no),
 CONSTRAINT sand_license_claim_secret_unique UNIQUE(secret_hash)
);
CREATE TABLE sand_license_redemption_code (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id bigint NOT NULL REFERENCES sand_license_product(id),
 plan_id bigint NOT NULL REFERENCES sand_license_plan(id),
 claim_id bigint REFERENCES sand_license_claim(id),
 prefix varchar(12) NOT NULL,
 secret_hash char(64) NOT NULL, pepper_version varchar(20) NOT NULL DEFAULT 'v1',
 state varchar(20) NOT NULL CHECK(state IN ('issued','redeemed','revoked','expired')),
 expire_time timestamp(0) without time zone NOT NULL,
 entitlement_id bigint REFERENCES sand_license_entitlement(id),
 create_time timestamp(0) without time zone NOT NULL,
 update_time timestamp(0) without time zone NOT NULL,
 CONSTRAINT sand_license_redemption_secret_unique UNIQUE(product_id,secret_hash)
);
ALTER TABLE sand_license_claim ADD CONSTRAINT sand_license_claim_code_fk FOREIGN KEY(redemption_code_id) REFERENCES sand_license_redemption_code(id);
CREATE TABLE sand_license_activation (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 entitlement_id bigint NOT NULL REFERENCES sand_license_entitlement(id),
 installation_key_thumbprint varchar(64) NOT NULL,
 public_key jsonb NOT NULL,
 name varchar(120) NOT NULL DEFAULT '',
 state varchar(20) NOT NULL CHECK(state IN ('active','released','revoked')),
 released_time timestamp(0) without time zone,
 seat_available_time timestamp(0) without time zone,
 create_time timestamp(0) without time zone NOT NULL,
 update_time timestamp(0) without time zone NOT NULL,
 CONSTRAINT sand_license_activation_key_unique UNIQUE(entitlement_id,installation_key_thumbprint)
);
CREATE TABLE sand_license_lease (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 activation_id bigint NOT NULL REFERENCES sand_license_activation(id),
 jti_hash char(64) NOT NULL, kid varchar(80) NOT NULL,
 state varchar(20) NOT NULL CHECK(state IN ('issued','revoked')),
 issued_time timestamp(0) without time zone NOT NULL,
 expire_time timestamp(0) without time zone NOT NULL,
 revoked_time timestamp(0) without time zone,
 CONSTRAINT sand_license_lease_jti_unique UNIQUE(jti_hash),
 CONSTRAINT sand_license_lease_interval_check CHECK(issued_time<expire_time)
);
CREATE INDEX sand_license_lease_activation_expire_idx ON sand_license_lease(activation_id,expire_time);
CREATE TABLE sand_license_challenge (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id bigint NOT NULL REFERENCES sand_license_product(id),
 purpose varchar(20) NOT NULL CHECK(purpose IN ('redeem','renew','current','release','enroll','ticket')),
 installation_key_thumbprint varchar(64) NOT NULL,
 secret_hash char(64) NOT NULL, proof_jti_hash char(64),
 state varchar(20) NOT NULL CHECK(state IN ('issued','consumed')),
 expire_time timestamp(0) without time zone NOT NULL,
 consumed_time timestamp(0) without time zone,
 create_time timestamp(0) without time zone NOT NULL,
 CONSTRAINT sand_license_challenge_secret_unique UNIQUE(secret_hash),
 CONSTRAINT sand_license_challenge_proof_unique UNIQUE(proof_jti_hash)
);
CREATE TABLE sand_license_enrollment_ticket (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 entitlement_id bigint NOT NULL REFERENCES sand_license_entitlement(id),
 source_activation_id bigint REFERENCES sand_license_activation(id),
 secret_hash char(64) NOT NULL,
 state varchar(20) NOT NULL CHECK(state IN ('issued','consumed','revoked')),
 available_time timestamp(0) without time zone NOT NULL,
 expire_time timestamp(0) without time zone NOT NULL,
 create_time timestamp(0) without time zone NOT NULL,
 update_time timestamp(0) without time zone NOT NULL,
 CONSTRAINT sand_license_enrollment_secret_unique UNIQUE(secret_hash),
 CONSTRAINT sand_license_enrollment_interval_check CHECK(available_time<expire_time)
);
CREATE TABLE sand_license_request_dedup (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id bigint NOT NULL REFERENCES sand_license_product(id),
 scope varchar(160) NOT NULL,
 idempotency_key_hash char(64) NOT NULL, request_hash char(64) NOT NULL,
 state varchar(20) NOT NULL CHECK(state IN ('succeeded')),
 result_ref jsonb NOT NULL,
 create_time timestamp(0) without time zone NOT NULL,
 CONSTRAINT sand_license_request_dedup_unique UNIQUE(product_id,scope,idempotency_key_hash)
);
CREATE TABLE sand_license_event (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id bigint NOT NULL REFERENCES sand_license_product(id),
 action varchar(80) NOT NULL, object_type varchar(80) NOT NULL,
 object_id bigint, actor_ref varchar(160) NOT NULL,
 request_id varchar(160) NOT NULL, reason_code varchar(160) NOT NULL DEFAULT '',
 detail jsonb NOT NULL DEFAULT '{}'::jsonb,
 create_time timestamp(0) without time zone NOT NULL
);

-- Shared host menu rows only; identity IDs are allocated by PostgreSQL.
-- Do not assign these menus to roles here. Host superadmin and explicit role grants apply.
-- SAND_LICENSE_MENU_BEGIN
DO $sand_license_menu$
DECLARE
 root_id bigint;
 page_id bigint;
 permission_id bigint;
 row_count integer;
 permission record;
BEGIN
 SELECT count(*), min(id) INTO row_count, root_id FROM sand_system_menu WHERE code = 'SandLicense';
 IF row_count > 1 THEN RAISE EXCEPTION 'SandLicense menu root is duplicated'; END IF;
 IF row_count = 0 THEN
  INSERT INTO sand_system_menu (parent_id,name,code,slug,type,path,component,icon,sort,is_hidden,status,create_time,update_time)
  VALUES (0,'商业授权','SandLicense','',1,'/plugin/sand-license','','ri:key-2-line',95,2,1,CURRENT_TIMESTAMP AT TIME ZONE 'UTC',CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
  RETURNING id INTO root_id;
 ELSIF NOT EXISTS (SELECT 1 FROM sand_system_menu WHERE id=root_id AND parent_id=0 AND type=1 AND path='/plugin/sand-license' AND component='' AND slug='' AND delete_time IS NULL) THEN
  RAISE EXCEPTION 'SandLicense root menu ownership conflicts';
 END IF;
 SELECT count(*), min(id) INTO row_count, page_id FROM sand_system_menu WHERE code = 'SandLicenseCenter';
 IF row_count > 1 THEN RAISE EXCEPTION 'SandLicense center menu is duplicated'; END IF;
 IF row_count = 0 THEN
  INSERT INTO sand_system_menu (parent_id,name,code,slug,type,path,component,icon,sort,is_hidden,status,create_time,update_time)
  VALUES (root_id,'商业许可','SandLicenseCenter','',2,'index','/plugin/sand-license/index/index','ri:key-2-line',100,2,1,CURRENT_TIMESTAMP AT TIME ZONE 'UTC',CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
  RETURNING id INTO page_id;
 ELSIF NOT EXISTS (SELECT 1 FROM sand_system_menu WHERE id=page_id AND parent_id=root_id AND type=2 AND path='index' AND component='/plugin/sand-license/index/index' AND slug='' AND delete_time IS NULL) THEN
  RAISE EXCEPTION 'SandLicense center menu ownership conflicts';
 END IF;
 FOR permission IN SELECT * FROM (VALUES
  ('sand_license:product:index','软件产品列表'),
  ('sand_license:product:read','软件产品详情'),
  ('sand_license:product:save','保存软件产品'),
  ('sand_license:product:publish','发布软件产品'),
  ('sand_license:plan:index','套餐列表'),
  ('sand_license:plan:read','套餐详情'),
  ('sand_license:plan:save','保存套餐'),
  ('sand_license:plan:publish','发布套餐'),
  ('sand_license:code:index','卡密列表'),
  ('sand_license:code:read','卡密详情'),
  ('sand_license:code:issue','手工发码与结果查询'),
  ('sand_license:code:reissue','重新签发卡密'),
  ('sand_license:code:revoke','撤销卡密'),
  ('sand_license:entitlement:index','权益列表'),
  ('sand_license:entitlement:read','权益详情'),
  ('sand_license:entitlement:suspend','暂停权益'),
  ('sand_license:entitlement:revoke','撤销权益'),
  ('sand_license:entitlement:ticket','签发新设备资格'),
  ('sand_license:activation:index','设备激活列表'),
  ('sand_license:activation:read','设备激活详情'),
  ('sand_license:activation:release','释放设备'),
  ('sand_license:activation:reset','重置设备'),
  ('sand_license:sku_mapping:index','商品映射列表'),
  ('sand_license:sku_mapping:read','商品映射详情'),
  ('sand_license:sku_mapping:save','保存商品映射'),
  ('sand_license:fulfillment:index','履约列表'),
  ('sand_license:fulfillment:read','履约详情'),
  ('sand_license:membership:index','会员权益列表'),
  ('sand_license:membership:read','会员权益详情'),
  ('sand_license:event:index','操作记录列表'),
  ('sand_license:event:read','操作记录详情')
 ) AS definition(slug,name) LOOP
  SELECT count(*), min(id) INTO row_count, permission_id FROM sand_system_menu WHERE code=permission.slug OR slug=permission.slug;
  IF row_count > 1 THEN RAISE EXCEPTION 'SandLicense permission is duplicated: %', permission.slug; END IF;
  IF row_count = 0 THEN
   INSERT INTO sand_system_menu (parent_id,name,code,slug,type,path,component,icon,sort,is_hidden,status,create_time,update_time)
   VALUES (page_id,permission.name,permission.slug,permission.slug,3,'','','',100,1,1,CURRENT_TIMESTAMP AT TIME ZONE 'UTC',CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
   RETURNING id INTO permission_id;
  ELSIF NOT EXISTS (SELECT 1 FROM sand_system_menu WHERE id=permission_id AND parent_id=page_id AND code=permission.slug AND slug=permission.slug AND type=3 AND path='' AND component='' AND delete_time IS NULL) THEN
   RAISE EXCEPTION 'SandLicense permission ownership conflicts: %', permission.slug;
  END IF;
 END LOOP;
END;
$sand_license_menu$;
-- SAND_LICENSE_MENU_END
CREATE INDEX sand_license_event_product_time_idx ON sand_license_event(product_id,create_time);
